version: '3.8'

services:
    main:
        container_name: minisom
        image: minisom
        build:
            context: .
            args:
                USER_ID: ${USER_ID?err}
                USER_GROUP_ID: ${USER_GROUP_ID?err}
        entrypoint: tail -f /dev/null
        volumes:
            - .:/work
            - ${HOST_SSH_KEYS_DIR?err}:/home/ds/.ssh
        environment:
            PYTHONPATH: /work/src:${PYTHON_PATH-}


        #Habilitando os drivers da GPU, caso uma esteja presente.
        #Se não tiver, não precisa remover esta seção. 
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
